{% set version = '0.3.16' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cansim
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cansim_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cansim/cansim_{{ version }}.tar.gz
  sha256: e2a243e89f96becf6dd43b03f6e88fb95848030eaf674df5d7607542d83f9790

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-digest >=0.1
    - r-dplyr >=0.7
    - r-httr >=1.0.0
    - r-jsonlite >=1.0
    - r-purrr
    - r-readr
    - r-rlang
    - r-rvest
    - r-stringr
    - r-tibble
    - r-xml2
  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - r-digest >=0.1
    - r-dplyr >=0.7
    - r-httr >=1.0.0
    - r-jsonlite >=1.0
    - r-purrr
    - r-readr
    - r-rlang
    - r-rvest
    - r-stringr
    - r-tibble
    - r-xml2

test:
  commands:
    - $R -e "library('cansim')"           # [not win]
    - "\"%R%\" -e \"library('cansim')\""  # [win]

about:
  home: https://github.com/mountainMath/cansim, https://mountainmath.github.io/cansim/, https://www.statcan.gc.ca/
  license: MIT
  summary: Searches for, accesses, and retrieves new-format and old-format Statistics Canada
    data tables, as well as individual vectors, as tidy data frames. This package deals
    with encoding issues, allows for bilingual English or French language data retrieval,
    and bundles convenience functions to make it easier to work with retrieved table
    data. Optional caching features are provided.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - vitodelgrec

# Package: cansim
# Type: Package
# Title: Accessing Statistics Canada Data Table and Vectors
# Version: 0.3.16
# Authors@R: c( person("Jens", "von Bergmann", email = "jens@mountainmath.ca", role = c("cre")), person("Dmitry", "Shkolnik", email = "shkolnikd@gmail.com", role = c("aut")))
# Maintainer: Jens von Bergmann <jens@mountainmath.ca>
# Description: Searches for, accesses, and retrieves new-format and old-format Statistics Canada data tables, as well as individual vectors, as tidy data frames. This package deals with encoding issues, allows for bilingual English or French language data retrieval, and bundles convenience functions to make it easier to work with retrieved table data. Optional caching features are provided.
# License: MIT + file LICENSE
# Encoding: UTF-8
# ByteCompile: yes
# NeedsCompilation: no
# LazyData: true
# Depends: R (>= 2.10)
# Imports: digest (>= 0.1), dplyr (>= 0.7), httr (>= 1.0.0), jsonlite (>= 1.0), readr, rlang, xml2, rvest, stringr, purrr, tibble, utils, DBI, RSQLite
# RoxygenNote: 7.2.3
# Suggests: knitr, rmarkdown, scales, tidyr, ggplot2, dbplyr
# URL: https://github.com/mountainMath/cansim, https://mountainmath.github.io/cansim/, https://www.statcan.gc.ca/
# BugReports: https://github.com/mountainMath/cansim/issues
# VignetteBuilder: knitr
# Language: en-CA
# Packaged: 2024-03-12 19:04:32 UTC; jens
# Author: Jens von Bergmann [cre], Dmitry Shkolnik [aut]
# Repository: CRAN
# Date/Publication: 2024-03-12 19:20:02 UTC
